src/Entity/Pokemon.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="pokemon")
 * @ORM\Entity(repositoryClass="App\Repository\PokemonRepository")
 */
class Pokemon
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $num;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $name;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\PkmType", cascade={"persist"})
     */
    private $types;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Ability", cascade={"persist"})
     */
    private $abilities;

    /**
     * @ORM\Column(type="integer",name="base_stat_pv")
     */
    private $baseStat_Pv;

    /**
     * @ORM\Column(type="integer",name="base_stat_atk")
     */
    private $baseStat_Atk;

    /**
     * @ORM\Column(type="integer",name="base_stat_def")
     */
    private $baseStat_Def;

    /**
     * @ORM\Column(type="integer",name="base_stat_spa")
     */
    private $baseStat_SpA;

    /**
     * @ORM\Column(type="integer",name="base_stat_spd")
     */
    private $baseStat_SpD;

    /**
     * @ORM\Column(type="integer",name="base_stat_spe")
     */
    private $baseStat_Spe;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Move", cascade={"persist"})
     */
    private $moves;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNum(): ?int
    {
        return $this->num;
    }

    public function setNum(int $num): self
    {
        $this->num = $num;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getTypes()
    {
        return $this->types;
    }
    
    public function addType(PkmType $type)
    {
        $this->types[] = $type;
    }

    public function removeType(PkmType $type)
    {
        $this->types->removeElement($type);
    }

    public function getAbilities()
    {
        return $this->abilities;
    }

    public function addAbility(Ability $ability)
    {
        $this->abilities[] = $ability;
    }

    public function removeAbility(Ability $ability)
    {
        $this->abilities->removeElement($ability);
    }

    public function getBaseStatPv(): ?int
    {
        return $this->baseStat_Pv;
    }

    public function setBaseStatPv(int $baseStat_Pv): self
    {
        $this->baseStat_Pv = $baseStat_Pv;

        return $this;
    }

    public function getBaseStatAtk(): ?int
    {
        return $this->baseStat_Atk;
    }

    public function setBaseStatAtk(int $baseStat_Atk): self
    {
        $this->baseStat_Atk = $baseStat_Atk;

        return $this;
    }

    public function getBaseStatDef(): ?int
    {
        return $this->baseStat_Def;
    }

    public function setBaseStatDef(int $baseStat_Def): self
    {
        $this->baseStat_Def = $baseStat_Def;

        return $this;
    }

    public function getBaseStatSpA(): ?int
    {
        return $this->baseStat_SpA;
    }

    public function setBaseStatSpA(int $baseStat_SpA): self
    {
        $this->baseStat_SpA = $baseStat_SpA;

        return $this;
    }

    public function getBaseStatSpD(): ?int
    {
        return $this->baseStat_SpD;
    }

    public function setBaseStatSpD(int $baseStat_SpD): self
    {
        $this->baseStat_SpD = $baseStat_SpD;

        return $this;
    }

    public function getBaseStatSpe(): ?int
    {
        return $this->baseStat_Spe;
    }

    public function setBaseStatSpe(int $baseStat_Spe): self
    {
        $this->baseStat_Spe = $baseStat_Spe;

        return $this;
    }

    public function getMoves()
    {
        return $this->moves;
    }
    
    public function addMove(Move $move)
    {
        $this->moves[] = $move;
    }

    public function removeMove(Move $move)
    {
        $this->moves->removeElement($move);
    }
}

src/Controller/BuildController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\Build;
use App\Entity\Image;
use App\Entity\Pokemon;
use App\Entity\Ability;
use App\Entity\Move;
use App\Entity\Nature;

/**
 * @Route("/symfodex")
 */
class BuildController extends AbstractController
{
    /**
     * @Route("/{page}", name="sd_pok_index", requirements={"page"="\d+"}, defaults={"page" = 1})
     */
    public function indexAction($page) {
        if($page < 1) {
            throw $this->createNotFoundException('page "'.$page.'" inexistant.');
        }
        
        //To do : create config
        $nbPerPage = 5;

        $repositories = self::getRepositories(array('Build'));

        $listBuilds = $repositories['Build']->getBuilds($page, $nbPerPage);

        $nbPages = ceil(count($listBuilds) / $nbPerPage);

        if($page > $nbPages) {
            throw $this->createNotFoundException('page "'.$page.'" inexistant.');
        }

        return $this->render('Symfodex/Build/index.html.twig', array(
            'listBuild' => $listBuilds,
            'nbPages' => $nbPages,
            'page' => $page
        ));
    }

    /**
     * @Route("/add", name="sd_pok_add")
     */
    public function addBuildAction(Request $request) {
        $repositories = self::getRepositories(array('Pokemon', 'Image'));
        $build = new Build();                      

        $form = self::createBuildForm($build);

        if($request->isMethod('POST')) {

            if($request->isXmlHttpRequest()) {
                $build = self::ajaxPostPokemonTreatment($request, $build, $repositories);
            } else {
                $form->handleRequest($request);
                if($form->isValid()) {
                    //To do : add more inputs verification

                    $build = self::formPostTreatment($build, $repositories);
                    return $this->redirectToRoute('sd_pok_view', array('id' => $build->getId()));
                }
            }
        } 

        return $this->render('Symfodex/Build/addBuild.html.twig', array(
            'form' => $form->createView(),
            'build' => $build
        ));
    }

    /**
     * @Route("/view/{id}", name="sd_pok_view", requirements={"id" = "\d+"})
     */
    public function viewAction($id) {
        $repositories = self::getRepositories(array('Build'));

        $build = $repositories['Build']->find($id);
        if(is_null($build)) {
            throw new \Exception("Le build d'id ".$id." n'esxiste pas.");
        }

        return $this->render('Symfodex/Build/viewBuild.html.twig', array(
            'build' => $build
        ));
    }

    /**
     * @Route("/edit/{id}", name="sd_pok_edit", requirements={"id" = "\d+"})
     */
    public function editAction($id, Request $request) {
        $repositories = self::getRepositories(array('Build', 'Pokemon', 'Image'));

        $build = $repositories['Build']->find($id);
        if(is_null($build)) {
            throw new \Exception("Le build d'id ".$id." n'esxiste pas.");
        }

        $form = self::createBuildForm($build);

        if($request->isMethod('POST')) {

            if($request->isXmlHttpRequest()) {
                $build = self::ajaxPostPokemonTreatment($request, $build, $repositories);
            } else {
                $form->handleRequest($request);
                if($form->isValid()) {
                    //To do : add more inputs verification

                    $build = self::formPostTreatment($build, $repositories);
                    return $this->redirectToRoute('sd_pok_view', array('id' => $build->getId()));
                }
            }
        }

        return $this->render('Symfodex/Build/editBuild.html.twig', array(
            'form' => $form->createView(),
            'build' => $build
        ));
    }

    /**
     * @Route("/delete/{id}", name="sd_pok_delete", requirements={"id" = "\d+"})
     */
    public function deleteAction($id, Request $request) {
        $repositories = self::getRepositories(array('Build'));
        $build = $repositories['Build']->find($id);

        if(is_null($build)) {
            throw new \Exception("Le build d'id ".$id." n'esxiste pas.");
        }

        // empty form with CSRF field
        $form = $this->get('form.factory')->create();
        
        if ($request->isMethod('POST')) {
            $form->handleRequest($request);
            
            $em = $this->getDoctrine()->getManager();
            $em->remove($build);
            $em->flush();
        
            return $this->redirectToRoute('sd_pok_index');
        }
          
        return $this->render('Symfodex/Build/deleteBuild.html.twig', array(
            'build' => $build,
            'form'   => $form->createView(),
        ));
    }

    /**
     * input : limit of build number for lastCreatedBuilds action
     * return : 3 last builds
     */
    public function lastCreatedBuildsAction($limit = 3) {
        $repositories = self::getRepositories(array('Build'));

        $listBuilds = $repositories['Build']->findBy(array(), array('date' => 'desc'), $limit, 0);

        return $this->render('Symfodex/Build/lastCreatedBuilds.html.twig', array('listBuild' => $listBuilds));
    }

    

    /**
     * @Route("/setNature", name="sd_set_nat")
     * ajax post request only
     */
    public function setNature(Request $request) {
        $repositories = self::getRepositories(array('Nature'));
        if($request->isMethod('POST')) {
            if($request->isXmlHttpRequest()) {
                $natureId = intval($request->request->all()['natureId']);
                $nature =  $repositories['Nature']->find($natureId);
                if(is_null($nature)) {
                    throw new \Exception("La nature d'id ".$natureId." n'esxiste pas.");
                }
                return new JsonResponse(json_encode(array('Atk' => $nature->getAtkBonus(), 
                                                          'Def' => $nature->getDefBonus(),
                                                          'Spa' => $nature->getSpABonus(),
                                                          'Spd' => $nature->getSpDBonus(),
                                                          'Spe' => $nature->getSpeBonus())));
            }
        }
    }

    /**
     * input : $build (empty or not)
     * return : form for add/edit build
     */
    private function createBuildForm($build) {
        //$repositories = self::getRepositories(array('Ability', 'Move'));

        if(is_null($build)) {
            throw new \Exception("Error");
        }

        $formBuilder = $this->get('form.factory')->createBuilder(FormType::class, $build);
        $formBuilder->add('date', DateType::class)
                    ->add('title', TextType::class)
                    ->add('author', TextType::class)
                    ->add('pokemon', EntityType::class, ['class' => Pokemon::class, 'placeholder' => '', 'choice_label' => 'name'])
                    ->add('nature', EntityType::class, ['class' => Nature::class, 'choice_label' => 'name'])
                    ->add('evPv', IntegerType::class, array('required' => false, 'attr' => array('class' => 'ev pv')))
                    ->add('evAtk', IntegerType::class, array('required' => false, 'attr' => array('class' => 'ev atk')))
                    ->add('evDef', IntegerType::class, array('required' => false, 'attr' => array('class' => 'ev def')))
                    ->add('evSpa', IntegerType::class, array('required' => false, 'attr' => array('class' => 'ev spa')))
                    ->add('evSpd', IntegerType::class, array('required' => false, 'attr' => array('class' => 'ev spd')))
                    ->add('evSpe', IntegerType::class, array('required' => false, 'attr' => array('class' => 'ev spe')))
                    ->add('ivPv', IntegerType::class, array('required' => false, 'attr' => array('class' => 'iv pv')))
                    ->add('ivAtk', IntegerType::class, array('required' => false, 'attr' => array('class' => 'iv atk')))
                    ->add('ivDef', IntegerType::class, array('required' => false, 'attr' => array('class' => 'iv def')))
                    ->add('ivSpa', IntegerType::class, array('required' => false, 'attr' => array('class' => 'iv spa')))
                    ->add('ivSpd', IntegerType::class, array('required' => false, 'attr' => array('class' => 'iv spd')))
                    ->add('ivSpe', IntegerType::class, array('required' => false, 'attr' => array('class' => 'iv spe')))
                    ->add('content', TextareaType::class, array('required' => false))
                    ->add('ability', EntityType::class, ['class' => Ability::class, 'choice_label' => 'name'])
                    //->add('ability', EntityType::class, ['class' => Ability::class, 'query_builder' => function($repositories) {} ])
                    //->add('moves', EntityType::class, ['class' => Move::class, 'choice_label' => 'name'])
                    ->add('save', SubmitType::class);
        
        $form = $formBuilder->getForm();

        return $form;
    }

    /**
     * input : array of repo needed
     * return : repo var for all needed repo
     */
    private function getRepositories(array $reposNeeded) {
        if(empty($reposNeeded)) {
            throw new \Exception("Repo array empty.");

templates/Symfodex/Build/_form.html.twig
{{ form_start(form, {'attr': {'class': 'form-horizontal'}}) }}
{{ form_errors(form) }}

<div class="form-group">
	{{ form_label(form.date, "Date", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
	{{ form_errors(form.date) }}
	<div class="col-sm-10">
		{{ form_widget(form.date) }}
	</div>
</div>

<div class="form-group">
	{{ form_label(form.title, "Titre du build", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
	{{ form_errors(form.title) }}
	<div class="col-sm-6">
		{{ form_widget(form.title, {'attr': {'class': 'form-control'}}) }}
	</div>
</div>

<div class="form-group">
	{{ form_label(form.author, "Auteur du build", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
	{{ form_errors(form.author) }}
	<div class="col-sm-6">
		{{ form_widget(form.author, {'attr': {'class': 'form-control'}}) }}
	</div>
</div>

<div class="form-group">
	{{ form_label(form.pokemon, "Pokemon", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
	{{ form_errors(form.pokemon) }}
	<div class="col-sm-3">
		{{ form_widget(form.pokemon, {'attr': {'class': 'form-control choixPokemon'}}) }}
	</div>
</div>

<div id="subFormulaire" class="form-group" style="width:900px; margin:0 auto;">
	<div id="subFormcontent">
		{% if not build.pokemon is null %}	
		
		{% if not build.image is null %}
			<img src="{{ build.image.url }}" alt="{{ build.image.alt }}"> <br>
		{% endif %}
	
		{% if not build.pokemon.types.empty %}
			<p>Type(s) : 
				{% for type in build.pokemon.types %}
				  {{ type.name }}{% if not loop.last %}, {% endif %}
				{% endfor %}
			</p>	
		{% endif %}
		
		<table>
			<tr>
			  <td width="8%">
				<div class="form-group">Pv :</div>
			  </td>
			  <td width="8%">
				<div class="form-group" id="basePv">{{ build.pokemon.baseStatPv }}</div>
			  </td> 
			  <td width="30%"><div class="graphBar" id="barPv"></div></td>	
			  <td width="23%">
				<div class="form-group">
					{{ form_label(form.evPv, "EV.PV", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
					{{ form_errors(form.evPv) }}
					<div class="col-sm-6">
						{{ form_widget(form.evPv, {'attr': {'min': '0', 'max': '252', 'value': build.evPv|default('0')}}) }}
					</div>
				</div>
			  </td>
			  <td width="23%">
				<div class="form-group">
					{{ form_label(form.ivPv, "IV.PV", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
					{{ form_errors(form.ivPv) }}
					<div class="col-sm-6">
						{{ form_widget(form.ivPv, {'attr': {'min': '0', 'max': '31', 'value': build.ivPv|default('31')}}) }}
					</div>
				</div>
			  </td>
			  <td width="8%">
				<div class="form-group" id="totalPv"></div>
			  </td>
			</tr>
			<tr>
			  <td>
				<div class="form-group">Atk :</div>
			  </td>
			  <td>
				<div class="form-group" id="baseAtk">{{ build.pokemon.baseStatAtk }}</div>
			  </td>
			  <td><div class="graphBar" id="barAtk"></div></td>
			  <td>
				<div class="form-group">
					{{ form_label(form.evAtk, "EV.Atk", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
					{{ form_errors(form.evAtk) }}
					<div class="col-sm-6">
						{{ form_widget(form.evAtk, {'attr': {'min': '0', 'max': '252', 'value': build.evAtk|default('0')}}) }}
					</div>
				</div>
			  </td>
			  <td>
				<div class="form-group">
					{{ form_label(form.ivAtk, "IV.Atk", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
					{{ form_errors(form.ivAtk) }}
					<div class="col-sm-6">
						{{ form_widget(form.ivAtk, {'attr': {'min': '0', 'max': '31', 'value': build.ivAtk|default('31')}}) }}
					</div>
				</div>
			  </td>
			  <td>
				<div class="form-group" id="totalAtk"></div>
			  </td>
			</tr>
			<tr>
			  <td>
				<div class="form-group">Def :</div>
			  </td>
			  <td>
				<div class="form-group" id="baseDef">{{ build.pokemon.baseStatDef }}</div>
			  </td>
			  <td><div class="graphBar" id="barDef"></div></td>
			  <td>
				<div class="form-group">
					{{ form_label(form.evDef, "EV.Def", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
					{{ form_errors(form.evDef) }}
					<div class="col-sm-6">
						{{ form_widget(form.evDef, {'attr': {'min': '0', 'max': '252', 'value': build.evDef|default('0')}}) }}
					</div>
				</div>
			  </td>
			  <td>
				<div class="form-group">
					{{ form_label(form.ivDef, "IV.Def", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
					{{ form_errors(form.ivDef) }}
					<div class="col-sm-6">
						{{ form_widget(form.ivDef, {'attr': {'min': '0', 'max': '31', 'value': build.ivDef|default('31')}}) }}
					</div>
				</div>
			  </td>
			  <td>
				<div class="form-group" id="totalDef"></div>
			  </td>
			</tr>
			<tr>
			  <td>
				<div class="form-group">Spa :</div>
			  </td>
			  <td>
				<div class="form-group" id="baseSpa">{{ build.pokemon.baseStatSpa }}</div>
			  </td>
			  <td><div class="graphBar" id="barSpa"></div></td>
			  <td>
				<div class="form-group">
					{{ form_label(form.evSpa, "EV.SpA", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
					{{ form_errors(form.evSpa) }}
					<div class="col-sm-6">
						{{ form_widget(form.evSpa, {'attr': {'min': '0', 'max': '252', 'value': build.evSpa|default('0')}}) }}
					</div>
				</div>
			  </td>
			  <td>
				<div class="form-group">
					{{ form_label(form.ivSpa, "IV.SpA", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
					{{ form_errors(form.ivSpa) }}
					<div class="col-sm-6">
						{{ form_widget(form.ivSpa, {'attr': {'min': '0', 'max': '31', 'value': build.ivSpa|default('31')}}) }}
					</div>
				</div>
			  </td>
			  <td>
				<div class="form-group" id="totalSpa"></div>
			  </td>
			</tr>
			<tr>
			  <td>
				<div class="form-group">Spd :</div>
			  </td>
			  <td>
				<div class="form-group" id="baseSpd">{{ build.pokemon.baseStatSpd }}</div>
			  </td>
			  <td><div class="graphBar" id="barSpd"></div></td>
			  <td>
				<div class="form-group">
					{{ form_label(form.evSpd, "EV.SpD", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
					{{ form_errors(form.evSpd) }}
					<div class="col-sm-6">
						{{ form_widget(form.evSpd, {'attr': {'min': '0', 'max': '252', 'value': build.evSpd|default('0')}}) }}
					</div>
				</div>
			  </td>
			  <td>
				<div class="form-group">
					{{ form_label(form.ivSpd, "IV.SpD", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
					{{ form_errors(form.ivSpd) }}
					<div class="col-sm-6">
						{{ form_widget(form.ivSpd, {'attr': {'min': '0', 'max': '31', 'value': build.ivSpd|default('31')}}) }}
					</div>
				</div>
			  </td>
			  <td>
				<div class="form-group" id="totalSpd"></div>
			  </td>
			</tr>
			<tr>
			  <td>
				<div class="form-group">Spe :</div>
			  </td>
			  <td>
				<div class="form-group" id="baseSpe">{{ build.pokemon.baseStatSpe }}</div>
			  </td>
			  <td><div class="graphBar" id="barSpe"></div></td>
			  <td>
				<div class="form-group">
					{{ form_label(form.evSpe, "EV.Spe", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
					{{ form_errors(form.evSpe) }}
					<div class="col-sm-6">
						{{ form_widget(form.evSpe, {'attr': {'min': '0', 'max': '252', 'value': build.evSpe|default('0')}}) }}
					</div>
				</div>
			  </td>
			  <td>
				<div class="form-group">
					{{ form_label(form.ivSpe, "IV.Spe", {'label_attr': {'class': 'col-sm-3 control-label'}}) }}
					{{ form_errors(form.ivSpe) }}
					<div class="col-sm-6">
						{{ form_widget(form.ivSpe, {'attr': {'min': '0', 'max': '31', 'value': build.ivSpe|default('31')}}) }}
					</div>
				</div>
			  </td>
			  <td>
				<div class="form-group" id="totalSpe"></div>
			  </td>
			</tr>
		</table>
		
		<span>Remaining : <span id="evRemaining">510</span></span>
		
		<div class="form-group">
			{{ form_label(form.nature, "Nature", {'label_attr': {'class': 'col-sm-1 control-label'}}) }}
			{{ form_errors(form.nature) }}
			<div class="col-sm-3">
				{{ form_widget(form.nature, {'attr': {'class': 'form-control choixNature', 'value': build.nature.id|default('1')}}) }}
			</div>
		</div>
		
		<div class="form-group">
			{{ form_label(form.ability, "Talent", {'label_attr': {'class': 'col-sm-1 control-label'}}) }}
			{{ form_errors(form.ability) }}
			<div class="col-sm-3">
				{{ form_widget(form.ability, {'attr': {'class': 'form-control choixTalent', 'value': build.ability.id|default('1')}}) }}
			</div>
		</div>
		
	{% endif %}
	</div>
</div>

<div class="form-group">
	{{ form_label(form.content, "Commentaires", {'label_attr': {'class': 'col-sm-2 control-label'}}) }}
	{{ form_errors(form.content) }}
	<div class="col-sm-6">
		{{ form_widget(form.content, {'attr': {'class': 'form-control'}}) }}
	</div>
</div>

{{ form_widget(form.save, {'attr': {'class': 'btn btn-primary'}}) }}

{{ form_end(form, {'render_rest': false}) }}

<script>
	$(document).ready(function () {
		setSubForm();
		setFormValidationEventListener();
		if(typeof($('.choixNature').val()) !== 'undefined') {
			setNatureBonus($('.choixNature').val());
		}
		setNatureBonusEventListener();
		setAllTotStat(true);
		setStatBar(true);
	});
</script>

templates/Symfodex/Build/addBuild.html.twig
{% extends "Symfodex/build_layout.html.twig" %}

{% block title %}{{ parent() }} - Add{% endblock %}

{% block sd_build_body %}

	<h2>Ajouter un build</h2>
	
	<div class="formulaire">
		{{ include("Symfodex/Build/_form.html.twig") }}
	</div>

{% endblock %}

templates/Symfodex/Build/deleteBuild.html.twig
{% extends "Symfodex/build_layout.html.twig" %}

{% block title %}{{ parent() }} - Delete{% endblock %}

{% block sd_build_body %}

	<h2>Supprimer un build.</h2>
	
	<p>
		Etes-vous certain de vouloir supprimer le build "{{ build.title }}" ?
	</p>
	
	<form action="{{ path('sd_pok_delete', {'id': build.id}) }}" method="post">
		<a href="{{ path('sd_pok_view', {'id': build.id}) }}" class="btn btn-default">
			<i class="glyphicon glyphicon-chevron-left"></i>
			Retour au build
		</a>
		
		<input type="submit" value="Supprimer" class="btn btn-danger" />
		
	</form>

{% endblock %}

templates/Symfodex/Build/editBuild.html.twig
{% extends "Symfodex/build_layout.html.twig" %}

{% block title %}{{ parent() }} - Edit{% endblock %}

{% block sd_build_body %}

	<h2>Modifier un build</h2>
	
	<div class="formulaire">
		{{ include("Symfodex/Build/_form.html.twig") }}
	</div>
	
	<br>
	
	<p>
		<a href="{{ path('sd_pok_view', {'id': build.id}) }}" class="btn btn-default">
			<i class="glyphicon glyphicon-chevron-left"></i>
			Retour au build
		</a>
	</p>
	
{% endblock %}

templates/Symfodex/Build/index.html.twig
{% extends "Symfodex/build_layout.html.twig" %}

{% block title %}
	Accueil - {{ parent() }}
{% endblock %}

{% block sd_build_body %}
	<h2>Liste des builds</h2>
	<ul>
		{% for build in listBuild %}
			<li>
				<a href="{{ path('sd_pok_view', {'id': build.id}) }}">
					{{ build.title }}
				</a>
				par {{ build.author }}
			</li>
		{% else %}
			<li>Pas (encore) de build</li>
		{% endfor %}
	</ul>
	
	<ul class="pagination">
	  {% for p in range(1, nbPages) %}
		<li{% if p == page %} class="active"{% endif %}>
		  <a href="{{ path('sd_pok_index', {'page': p}) }}">{{ p }}</a>
		</li>
	  {% endfor %}
	</ul>

{% endblock %}

templates/Symfodex/Build/lastCreatedBuilds.html.twig
<ul class="nav nav-pills nav-stacked">
	{% for build in listBuild %}
		<li>
			<a href="{{ path('sd_pok_view', {'id': build.id}) }}">
				{{ build.title }}
			</a>
		</li>
	{% endfor %}
</ul>;